#!/usr/bin/env bash
# PreToolUse(Edit|Write): deny edits to GENERATED / vendored artifacts — the source
# is elsewhere and the artifact is rebuilt. Denies via permissionDecision JSON.
set -u
command -v jq >/dev/null 2>&1 || exit 0
f=$(jq -r '.tool_input.file_path // empty' 2>/dev/null)
[ -n "$f" ] || exit 0

deny() {
  jq -cn --arg r "$1" \
    '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:$r}}'
  exit 0
}

case "$f" in
  */web-ui/dist/*)                     deny "web-ui/dist is a build artifact (rust-embed serves it) — edit web-ui/src and rebuild." ;;
  */target/*|*/chimaera-app/target/*)  deny "target/ is cargo build output — edit the source crate." ;;
  */node_modules/*)                    deny "node_modules is vendored — change package.json, not a dep." ;;
  */.chimaera-dev/*)                   deny ".chimaera-dev is the isolated daemon's runtime state — not source." ;;
  */crates/chimaera-app/gen/*)         deny "chimaera-app/gen is Tauri-generated." ;;
  */permissions/autogenerated/*)       deny "permissions/autogenerated/*.toml is generated by tauri-build — change the command list, then rebuild." ;;
esac
exit 0
