#!/usr/bin/env python3
"""Regenerate the committed Tabler icon manifest.

Run at *authoring time* only — the daemon must never depend on node_modules at
build time, so this reads the @tabler/icons package once and commits three
compact artifacts next to it:

    tabler-outline.txt   name<TAB>d1<TAB>d2...   (the drawing paths)
    tabler-meta.txt      name<TAB>category<TAB>tag,tag,...   (discovery index)
    LICENSE-tabler       the upstream MIT license, verbatim

Only the **outline** style is used (24x24 viewBox, stroke="currentColor",
stroke-width 2, round caps/joins — the whole set is uniform, verified). The
invisible background rect (`M0 0h24v24H0z`, stroke:none fill:none) is dropped.
The rare filled path (`fill="currentColor"`, ~77 of ~20.6k paths) is marked
with a leading `~` so the renderer paints it filled instead of stroked. One
path carries an `opacity` that is intentionally dropped (drawn fully opaque).

Usage:
    python3 generate.py [PATH_TO_@tabler/icons]

Source pin: recorded in the header of tabler-outline.txt (package version +
git commit are stamped from package.json). Keep that pin and this script in
sync so the manifest is reproducible.
"""

import glob
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_PKG = os.path.abspath(
    os.path.join(HERE, "../../../../web-ui/node_modules/@tabler/icons")
)

PATH_RE = re.compile(r"<path\b([^>]*)/>", re.S)
D_RE = re.compile(r'\bd="([^"]*)"')


def main() -> int:
    pkg = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_PKG
    outdir = os.path.join(pkg, "icons", "outline")
    if not os.path.isdir(outdir):
        print(f"no outline set at {outdir}", file=sys.stderr)
        return 1

    version = "unknown"
    try:
        with open(os.path.join(pkg, "package.json")) as fh:
            version = json.load(fh).get("version", "unknown")
    except OSError:
        pass

    files = sorted(glob.glob(os.path.join(outdir, "*.svg")))
    lines = []
    for f in files:
        name = os.path.splitext(os.path.basename(f))[0]
        with open(f) as fh:
            txt = fh.read()
        parts = [name]
        for m in PATH_RE.finditer(txt):
            attrs = m.group(1)
            dm = D_RE.search(attrs)
            if not dm:
                continue
            d = dm.group(1).strip()
            # Drop the invisible full-bleed background rect.
            if 'stroke="none"' in attrs and 'fill="none"' in attrs:
                continue
            if d == "M0 0h24v24H0z":
                continue
            filled = 'fill="currentColor"' in attrs
            parts.append(("~" if filled else "") + d)
        # An icon with no drawing paths is not worth an entry.
        if len(parts) > 1:
            lines.append("\t".join(parts))

    header = (
        f"# Tabler Icons outline set, v{version} — MIT (see LICENSE-tabler).\n"
        "# name<TAB>d... ; viewBox is 0 0 24 24 and stroke-width 2 for every\n"
        "# entry; a leading ~ marks a filled path. Generated by generate.py;\n"
        "# do not hand-edit.\n"
    )
    manifest = header + "\n".join(lines) + "\n"
    with open(os.path.join(HERE, "tabler-outline.txt"), "w") as fh:
        fh.write(manifest)

    # Discovery metadata: category + tags, from the package's icons.json.
    meta = {}
    try:
        with open(os.path.join(pkg, "icons.json")) as fh:
            meta = json.load(fh)
    except OSError:
        pass
    names = {os.path.splitext(os.path.basename(f))[0] for f in files}
    mlines = []
    for name in sorted(names):
        entry = meta.get(name, {})
        cat = (entry.get("category") or "").strip()
        tags = ",".join(str(t).strip() for t in entry.get("tags", []) if str(t).strip())
        mlines.append(f"{name}\t{cat}\t{tags}")
    mheader = (
        f"# Tabler Icons outline discovery index, v{version} — MIT.\n"
        "# name<TAB>category<TAB>tag,tag,... ; parsed lazily only by the\n"
        "# `chimaera board icons` verb. Generated by generate.py.\n"
    )
    with open(os.path.join(HERE, "tabler-meta.txt"), "w") as fh:
        fh.write(mheader + "\n".join(mlines) + "\n")

    # The upstream license, verbatim.
    for cand in ("LICENSE", "LICENSE.md", "license"):
        src = os.path.join(pkg, cand)
        if os.path.exists(src):
            with open(src) as fh:
                lic = fh.read()
            with open(os.path.join(HERE, "LICENSE-tabler"), "w") as fh:
                fh.write(lic)
            break

    print(
        f"wrote {len(lines)} icons "
        f"({os.path.getsize(os.path.join(HERE, 'tabler-outline.txt'))} bytes) "
        f"+ meta from Tabler v{version}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
