//! The bundled icon set: Tabler Icons, *outline* style.
//!
//! Source: `@tabler/icons` v3.45.0 (MIT — the license travels with us at
//! `src/icons/LICENSE-tabler`; copyright Paweł Kuna). The 5,112 outline glyphs
//! are committed as one compact manifest (`src/icons/tabler-outline.txt`,
//! ~900 KB) generated by `src/icons/generate.py`, so the daemon *never* reads
//! `node_modules` at build time and stays one static musl binary. The whole
//! outline set is uniform — a 24×24 viewBox, `stroke="currentColor"`,
//! stroke-width 2, round caps/joins — so the manifest stores only `name → the
//! drawing path `d` strings`; the invisible full-bleed background rect is
//! dropped and the rare filled path is flagged (a leading `~`).
//!
//! Gated behind the default-on `icons` cargo feature (skippable like `math`).
//! The `Icon` object, its ceilings, and the missing-feature refusal compile in
//! every build; only the manifest data and its parse are feature-gated, so a
//! `--no-default-features` build renders a placeholder-with-reason for an icon
//! rather than failing to build. Embedded weight, measured: ~1.39 MB (paths +
//! the discovery index + the license), below the equation font's 1.65 MB.
//!
//! An icon is close kin to a `shape` with `geo:"path"`: the renderer fits the
//! 24×24 paths into the object box (aspect-preserving, centered) and strokes
//! them with a theme token; the PPTX exporter emits the same paths as editable
//! `custGeom` shapes so the user can "drag it down and polish".

use crate::schema::Frame;

/// The refusal a build without the `icons` feature surfaces. Callers pair it
/// with the standard placeholder so a missing feature is never a blank box.
pub const MISSING_FEATURE: &str =
    "this build lacks the icons feature (rebuild with default features or --features icons)";

/// The outline set's viewBox is a 24-unit square for every glyph.
pub const VIEW_BOX: f64 = 24.0;

/// Tabler's designed stroke weight, in viewBox units — the default when an
/// `icon` object states no `strokeWidth`. It scales with the icon because the
/// paths live in the 24-unit space that `fit` maps into the object box.
pub const DEFAULT_STROKE_WIDTH: f64 = 2.0;

/// Whether the manifest is compiled into this build.
pub const fn enabled() -> bool {
    cfg!(feature = "icons")
}

/// One drawing path of an icon: SVG path data in the 24×24 viewBox space, plus
/// whether it is a filled region (`fill="currentColor"`, a minority) or the
/// usual stroked outline.
#[derive(Debug, Clone, Copy)]
pub struct IconPath {
    pub d: &'static str,
    pub filled: bool,
}

/// A resolved icon: its name and its ordered drawing paths.
#[derive(Debug, Clone)]
pub struct Icon {
    pub name: &'static str,
    pub paths: Vec<IconPath>,
}

/// A discovery hit: the icon name and its Tabler category (for a grouped
/// print). Ordered by the discovery verb from best to broadest match.
#[derive(Debug, Clone, Copy)]
pub struct Match {
    pub name: &'static str,
    pub category: &'static str,
}

/// The centered, aspect-preserving fit of the 24×24 icon viewBox into a
/// page-space frame: a viewBox point `(px, py)` maps to
/// `(ox + px·scale, oy + py·scale)`. This is exactly SVG
/// `preserveAspectRatio="xMidYMid meet"`, so the renderer's nested `<svg>` and
/// the PPTX coordinate transform place identical geometry from one formula.
pub fn fit(f: Frame) -> (f64, f64, f64) {
    let scale = (f.w.min(f.h) / VIEW_BOX).max(0.0);
    let drawn = VIEW_BOX * scale;
    (scale, f.x + (f.w - drawn) / 2.0, f.y + (f.h - drawn) / 2.0)
}

/// Resolve a stated `strokeWidth` (viewBox units), falling back to Tabler's
/// designed weight for an absent or non-positive value.
pub fn stroke_width(stated: Option<f64>) -> f64 {
    match stated {
        Some(w) if w.is_finite() && w > 0.0 => w,
        _ => DEFAULT_STROKE_WIDTH,
    }
}

/// The named icon's paths, or `None` when the name is unknown *or* this build
/// omits the `icons` feature. Callers distinguish the two via [`enabled`] so
/// the diagnostic names the real reason.
pub fn lookup(name: &str) -> Option<&'static Icon> {
    #[cfg(feature = "icons")]
    {
        imp::map().get(name)
    }
    #[cfg(not(feature = "icons"))]
    {
        let _ = name;
        None
    }
}

/// The number of bundled icons (0 without the feature).
pub fn count() -> usize {
    #[cfg(feature = "icons")]
    {
        imp::map().len()
    }
    #[cfg(not(feature = "icons"))]
    {
        0
    }
}

/// Discovery: matches for `query`, ranked exact-name → name-prefix →
/// name-substring → category/tag, then alphabetical. An empty query lists
/// every icon (alphabetically). Returns nothing without the feature.
pub fn search(query: &str) -> Vec<Match> {
    #[cfg(feature = "icons")]
    {
        imp::search(query)
    }
    #[cfg(not(feature = "icons"))]
    {
        let _ = query;
        Vec::new()
    }
}

#[cfg(feature = "icons")]
mod imp {
    use std::collections::BTreeMap;
    use std::sync::OnceLock;

    use super::{Icon, IconPath, Match};

    const MANIFEST: &str = include_str!("icons/tabler-outline.txt");
    /// The discovery index (category + tags). Parsed lazily and only by the
    /// `icons` verb, so it costs no RSS on the render path.
    const META: &str = include_str!("icons/tabler-meta.txt");

    /// name → icon, parsed once. Values borrow the embedded `MANIFEST`, so the
    /// map is zero-copy over the static bytes.
    pub(super) fn map() -> &'static BTreeMap<&'static str, Icon> {
        static MAP: OnceLock<BTreeMap<&'static str, Icon>> = OnceLock::new();
        MAP.get_or_init(|| {
            let mut m = BTreeMap::new();
            for line in MANIFEST.lines() {
                if line.is_empty() || line.starts_with('#') {
                    continue;
                }
                let mut it = line.split('\t');
                let Some(name) = it.next() else { continue };
                let paths: Vec<IconPath> = it
                    .map(|p| match p.strip_prefix('~') {
                        Some(d) => IconPath { d, filled: true },
                        None => IconPath {
                            d: p,
                            filled: false,
                        },
                    })
                    .collect();
                if !paths.is_empty() {
                    m.insert(name, Icon { name, paths });
                }
            }
            m
        })
    }

    /// (name, category, tags) rows, parsed once for discovery.
    fn meta() -> &'static Vec<(&'static str, &'static str, &'static str)> {
        static META_ROWS: OnceLock<Vec<(&'static str, &'static str, &'static str)>> =
            OnceLock::new();
        META_ROWS.get_or_init(|| {
            META.lines()
                .filter(|l| !l.is_empty() && !l.starts_with('#'))
                .filter_map(|l| {
                    let mut it = l.splitn(3, '\t');
                    let name = it.next()?;
                    Some((name, it.next().unwrap_or(""), it.next().unwrap_or("")))
                })
                .collect()
        })
    }

    pub(super) fn search(query: &str) -> Vec<Match> {
        let q = query.trim().to_ascii_lowercase();
        let mut hits: Vec<(u8, &'static str, &'static str)> = Vec::new();
        for &(name, cat, tags) in meta() {
            let rank = if q.is_empty() {
                4
            } else if name == q {
                0
            } else if name.starts_with(&q) {
                1
            } else if name.contains(&q) {
                2
            } else if contains_ci(cat, &q) || contains_ci(tags, &q) {
                3
            } else {
                continue;
            };
            hits.push((rank, name, cat));
        }
        hits.sort_by(|a, b| a.0.cmp(&b.0).then(a.1.cmp(b.1)));
        hits.into_iter()
            .map(|(_, name, category)| Match { name, category })
            .collect()
    }

    /// Case-insensitive substring test without allocating on the common miss:
    /// `q` is already lowercase, and category/tag strings are short.
    fn contains_ci(haystack: &str, q: &str) -> bool {
        if haystack.is_empty() {
            return false;
        }
        haystack.to_ascii_lowercase().contains(q)
    }
}

#[cfg(all(test, feature = "icons"))]
mod tests {
    use super::*;

    #[test]
    fn manifest_loads_and_a_known_icon_has_paths() {
        assert!(count() > 5000, "the full outline set loads: {}", count());
        let flask = lookup("flask").expect("flask is a bundled icon");
        assert!(
            !flask.paths.is_empty(),
            "a known icon resolves to non-empty paths"
        );
        // Every path carries real SVG path data starting with a moveto.
        for p in &flask.paths {
            assert!(p.d.starts_with('M'), "path data is well formed: {}", p.d);
        }
    }

    #[test]
    fn an_unknown_name_resolves_to_none() {
        assert!(lookup("definitely-not-an-icon").is_none());
    }

    #[test]
    fn discovery_matches_names_and_synonyms() {
        let hits = search("flask");
        assert!(
            hits.iter().any(|m| m.name == "flask"),
            "a substring query finds the icon by name"
        );
        // A tag/synonym query surfaces icons whose *name* does not contain it:
        // "flask" is tagged "chemistry"/"laboratory".
        let syn = search("laboratory");
        assert!(
            syn.iter().any(|m| m.name == "flask"),
            "a synonym query finds the icon via its tags"
        );
        // Many arrows exist; the query is not empty-listing everything.
        let arrows = search("arrow");
        assert!(arrows.len() > 10, "arrow matches many icons");
        assert!(arrows.iter().all(|m| lookup(m.name).is_some()));
    }

    #[test]
    fn fit_centers_and_preserves_aspect() {
        // A wide box: the square icon is centered horizontally, flush top.
        let (scale, ox, oy) = fit(Frame {
            x: 10.0,
            y: 20.0,
            w: 48.0,
            h: 24.0,
        });
        assert!((scale - 1.0).abs() < 1e-9);
        assert!(
            (ox - (10.0 + 12.0)).abs() < 1e-9,
            "centered in the wide axis"
        );
        assert!((oy - 20.0).abs() < 1e-9, "flush in the tight axis");
    }
}
