//! One command vocabulary shared by the Tauri build-time permission generator
//! and the runtime daemon-window capability. `generate_handler!` remains the
//! compiler-checked dispatch side; wizard grants remain static and local-only.

pub const DAEMON_UI_COMMANDS: &[&str] = &[
    "list_hosts",
    "add_host",
    "remove_host",
    "connect_host",
    "disconnect_host",
    "end_host_sessions",
    "shutdown_host",
    "local_state",
    "update_local_daemon",
    "remote_workspaces",
    "cluster_overview",
    "cluster_facts",
    "cluster_add_workspace",
    "cluster_remove_workspace",
    "cluster_list_dir",
    "cluster_start_job",
    "cluster_continue_job",
    "cluster_stop_job",
    "cluster_dismiss_job",
    "cluster_open",
    "cluster_close",
    "cluster_move",
    "cluster_queue_open",
    "cluster_set_startup",
    "cluster_forget_setup",
    "cluster_set_agent_rules",
    "cluster_set_login_serve",
    "cluster_stop_login_daemon",
    "cluster_open_terminal",
    "open_window",
    "navigate_home",
    "open_detached_window",
    "drag_track",
    "drag_drop",
    "drag_cancel",
    "adopt_ack",
    "adopt_tab",
    "list_scope_windows",
    "report_window_scope",
    "report_window_view",
    "report_unsaved",
    "reply_unsaved",
    "take_pending_focus",
    "notification_permission",
    "request_notification_permission",
    "open_notification_settings",
    "test_notification",
    "check_app_update",
    "app_update_status",
    "begin_update",
    "shell_build",
    "write_clipboard",
    "open_external",
    "answer_askpass",
    "list_askpass",
    "cache_appearance",
];

// The application crate consumes only the daemon list at runtime; this list is
// consumed by the separately compiled build script.
#[allow(dead_code)]
pub const WSL_SETUP_COMMANDS: &[&str] = &[
    "wsl_status",
    "wsl_install",
    "wsl_update",
    "wsl_install_distro",
    "wsl_setup_daemon",
];
