//! One command vocabulary shared by the Tauri build-time permission generator
//! and the runtime daemon-window capability. `generate_handler!` remains the
//! compiler-checked dispatch side; wizard grants remain static and local-only.
//! Every command must appear in exactly one list below.

pub const DAEMON_UI_COMMANDS: &[&str] = &[
    "list_hosts",
    "add_host",
    "remove_host",
    "connect_host",
    "disconnect_host",
    "end_host_sessions",
    "shutdown_host",
    "local_state",
    "update_local_daemon",
    "remote_workspaces",
    "cluster_overview",
    "cluster_facts",
    "cluster_add_workspace",
    "cluster_remove_workspace",
    "cluster_list_dir",
    "cluster_start_job",
    "cluster_continue_job",
    "cluster_stop_job",
    "cluster_dismiss_job",
    "cluster_open",
    "cluster_close",
    "cluster_move",
    "cluster_queue_open",
    "set_not_cluster",
    "cluster_set_startup",
    "cluster_forget_setup",
    "cluster_set_agent_rules",
    "cluster_set_login_serve",
    "cluster_stop_login_daemon",
    "cluster_open_terminal",
    "open_window",
    "navigate_home",
    "open_detached_window",
    "drag_track",
    "drag_drop",
    "drag_cancel",
    "adopt_ack",
    "adopt_tab",
    "list_scope_windows",
    "report_window_scope",
    "report_window_view",
    "report_unsaved",
    "reply_unsaved",
    "take_pending_focus",
    "notification_permission",
    "request_notification_permission",
    "open_notification_settings",
    "test_notification",
    "check_app_update",
    "app_update_status",
    "begin_update",
    "shell_build",
    "write_clipboard",
    "open_external",
    "answer_askpass",
    "list_askpass",
    "cache_appearance",
];

/// Account commands act on this computer's Pro sign-in (sign-out, device
/// removal, billing, provider codes, project privacy). They are granted only
/// to windows showing the LOCAL daemon's UI, never to a remote host's,
/// another computer's or the cloud's UI, which run code this shell does not
/// control.
pub const LOCAL_ACCOUNT_COMMANDS: &[&str] = &[
    "pro_cloud_request",
    "pro_cloud_status",
    "pro_status",
    "pro_refresh_account",
    "pro_cloud_projects",
    "pro_open_cloud_project",
    "pro_billing_checkout",
    "pro_billing_portal",
    "pro_cancel_billing",
    "pro_take_return",
    "pro_mirror_status",
    "pro_set_never_mirror",
    "pro_sign_in",
    "pro_cancel_sign_in",
    "pro_sign_out",
    "pro_sign_out_everywhere",
    "pro_hosts",
    "pro_set_host_kept",
    "pro_devices",
    "pro_revoke_device",
];

// The application crate consumes only the daemon lists at runtime; this list is
// consumed by the separately compiled build script.
#[allow(dead_code)]
pub const WSL_SETUP_COMMANDS: &[&str] = &[
    "wsl_status",
    "wsl_install",
    "wsl_update",
    "wsl_install_distro",
    "wsl_setup_daemon",
];

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn account_commands_are_local_only_and_permissions_match_exactly() {
        let all: Vec<&str> = DAEMON_UI_COMMANDS
            .iter()
            .chain(LOCAL_ACCOUNT_COMMANDS)
            .chain(WSL_SETUP_COMMANDS)
            .copied()
            .collect();
        let unique: HashSet<&str> = all.iter().copied().collect();
        assert_eq!(unique.len(), all.len(), "a command is listed twice");
        assert!(DAEMON_UI_COMMANDS.iter().all(|c| !c.starts_with("pro_")));
        assert!(LOCAL_ACCOUNT_COMMANDS.iter().all(|c| c.starts_with("pro_")));
        let dir =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("permissions/autogenerated");
        let committed: HashSet<String> = std::fs::read_dir(dir)
            .unwrap()
            .filter_map(|entry| {
                let name = entry.unwrap().file_name().into_string().unwrap();
                name.strip_suffix(".toml").map(str::to_owned)
            })
            .collect();
        let expected: HashSet<String> = all.iter().map(|c| c.to_string()).collect();
        assert_eq!(committed, expected, "permissions/autogenerated drifted");
    }
}
